return {
	Ability = "",
	Bounty = 0,
	
	Gem = 100,
	Kills = 0,
	
	Cash = 0,
	
	Deaths = 0,
	
	Mastery = {
		["Gojo"] = {MasteryLevel = 1, MasteryExperience = 0},
		["Sanji"] = {MasteryLevel = 1, MasteryExperience = 0},
		["Whitebeard"] = {MasteryLevel = 1, MasteryExperience = 0},
		["Deku"] = {MasteryLevel = 1, MasteryExperience = 0},
		["Sasuke"] = {MasteryLevel = 1, MasteryExperience = 0},

	},
	
	Slot1 = "",
	Slot2 = "",
	Slot3 = "",
	
	MaxOutfitSlot = 50,
	MaxWeaponSlot = 50,
	
	UnlockedFreeSlot = false,
	
	Codes = {},
	
	DonatedRobux = 0,
	
	Inventory = {
		ChatTitles = {},
		KillEffects = {},
		OverheadTitles = {},
		Outfits = {},
		Weapons = {},
		Emotes = {},
	},
	
	EquippedWeapon = "",
	
	EquippedItems = {
		Accessory  = "",
		Top = "",
		Bottom = ""
	},
	
	Boosts = {
		x2Exp = 0,
	},
	
	DailyQuests = {
		InitialTime = os.time() - 86400,
		
		Quests = {},
	}
}