return {
	["EmoteChest"] = {
		["Common"] = {"Crying"},
		["Uncommon"] = {"Laughing"},
		["Rare"] = {"Blood on Your Hands"},
		["Epic"] = {"Losing"},
		["Legendary"] = {"The Hero"}
	},
	["OutfitChest"] = {
		["Common"] = {"Zoro", "Kirito"},
		["Uncommon"] = {"Sasuke"},
		["Rare"] = {"Byakuya"},
		["Epic"] = {"Escanor"},
		["Legendary"] = {"Byakuya"}
	},
	
	["WeaponChest"] = {
		["Common"] = {"ShieldHero", "Climatact"},
		["Uncommon"] = {"Kubikiribocho", "Shusui"},
		["Rare"] = {"Demon Scythe", "Anti Magic Greatsword"},
		["Epic"] = {"Samehameda"},
		["Legendary"] = {"Bisento"}
	},
	
	["ChatTitleChest"] = {
		["Common"] = {"Maestro"},
		["Uncommon"] = {"Maestro"},
		["Rare"] = {"Maestro"},
		["Epic"] = {"Maestro"},
		["Legendary"] = {"Maestro"}
	}
	
}