return {
	
	--[[
	["Eyepatch"] = {	
		Rarity = "Common",
		Type = "Accessory",
		
		Buffs = {
			Defense = 20,
			Fruit = 20
		},
	},
	["Black Cape"] = {	
		Rarity = "Rare",
		Type = "Accessory",
		
		Buffs = {
			Defense = 20,
			Fruit = 20,
		},
	},
	
	["Crown"] = {	
		Rarity = "Legendary",
		Type = "Accessory",
		
		Buffs = {
			Defense = 20,
			Fruit = 20,
			Strength = 10,
		},
	},

	["Pirate Hat"] = {	
		Rarity = "Rare",
		Type = "Accessory",
		
		Buffs = {
			Defense = 20,
			Fruit = 20
		},
	},
--]]

	
	["Melee"] = {
		Rarity = "Common",
		Type = "Fighting Style",
		
		StatCategory = "Strength",
		
		MasteryCap = 100,
	},
	
	["Sanji"] = {
		Rarity = "Common",
		Type = "Ability",
		

		MasteryCap = 100,
	},
	
	["Deku"] = {
		Rarity = "Common",
		Type = "Ability",


		MasteryCap = 100,
	},
	["Whitebeard"] = {
		Rarity = "Legendary",
		Type = "Ability",


		MasteryCap = 100,
	},
	["Sasuke"] = {
		Rarity = "Common",
		Type = "Ability",


		MasteryCap = 100,
	},
	["Endeavor"] = {
		Rarity = "Epic",
		Type = "Ability",


		MasteryCap = 100,
	},
	["Naruto"] = {
		Rarity = "Rare",
		Type = "Ability",


		MasteryCap = 100,
	},
	["Katana"] = {
		Rarity = "Common",
		Type = "Sword Style",
		
		StatCategory = "Sword",
		
		MasteryCap = 100,
	},
	
	["Yoru"] = {
		Rarity = "Mythical",
		Type = "Sword Style",

		StatCategory = "Sword",

		MasteryCap = 100,
	},
	
	["Dual Katana"] = {
		Rarity = "Rare",
		Type = "Sword Style",

		StatCategory = "Sword",

		MasteryCap = 100,
	},
	
	["Ice"] = {
		Rarity = "Legendary",
		Type = "Devil Fruit",
		
		StatCategory = "Fruit",
		
		FruitType = "Logia",
		
		MasteryCap = 400
	},
	
	["Smoke"] = {
		Rarity = "Legendary",
		Type = "Devil Fruit",

		StatCategory = "Fruit",

		FruitType = "Logia",

		MasteryCap = 400
	},
	
	["Bomb"] = {
		Rarity = "Rare",
		Type = "Devil Fruit",

		StatCategory = "Fruit",
		
		
		FruitType = "Paramecium",
		
		MasteryCap = 100
	},
	["Light"] = {
		Rarity = "Legendary",
		Type = "Devil Fruit",

		StatCategory = "Fruit",
		
		FruitType = "Logia",
		
		MasteryCap = 400
	},
	
	
	["Flame"] = {
		Rarity = "Legendary",
		Type = "Devil Fruit",

		StatCategory = "Fruit",
		
		FruitType = "Logia",
		
		MasteryCap = 400
	},
	
}