return {
	["EmoteChest"] = {
		Price = 1000, --gems/ add category later?
		MaxPity = 100, --1/MaxPity
	},
	["OutfitChest"] = {
		Price = 1000, --gems/ add category later?
		MaxPity = 100, --1/MaxPity
	},
	["WeaponChest"] = {
		Price = 1000, --gems/ add category later?
		MaxPity = 100, --1/MaxPity
	},
	["ChatTitleChest"] = {
		Price = 1000, --gems/ add category later?
		MaxPity = 100, --1/MaxPity
	}
}